# Generated by Django 4.2.26 on 2025-12-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('APPO', 'アポ'), ('MEETING', '商談中'), ('PROPOSAL', '提案中'), ('WON', '受注'), ('LOST', '失注'), ('LOST_never', '永久失注')], default='APPO', max_length=10, verbose_name='進捗'),
        ),
    ]
